/**
 * Generated by @openapi-codegen
 *
 * @version v0
 */
export type Appointment = {
  /**
   * @format int64
   */
  id?: number;
  patient?: Patient;
  therapist?: Therapist;
  timeslot?: Timeslot;
};

export type ConstraintAnalysisHardSoftScore = {
  constraintRef?: ConstraintRef;
  weight?: HardSoftScore;
  score?: HardSoftScore;
  matches?: MatchAnalysisHardSoftScore[];
};

export type ConstraintJustification = Record<string, any>;

export type ConstraintRef = {
  packageName?: string;
  constraintName?: string;
  constraintId?: string;
};

export type HardSoftScore = {
  /**
   * @format int32
   * @deprecated true
   */
  initScore?: number;
  /**
   * @format int32
   * @deprecated true
   */
  hardScore?: number;
  /**
   * @format int32
   * @deprecated true
   */
  softScore?: number;
  feasible?: boolean;
  zero?: boolean;
  solutionInitialized?: boolean;
};

export type LatLng = {
  /**
   * @format double
   */
  latitude?: number;
  /**
   * @format double
   */
  longitude?: number;
  polar?: boolean;
  /**
   * @format int64
   */
  latitudeInternal?: number;
  /**
   * @format int64
   */
  longitudeInternal?: number;
};

export type LocalTime = {
  /**
   * @format int32
   */
  hour?: number;
  /**
   * @format int32
   */
  minute?: number;
  /**
   * @format int32
   */
  second?: number;
  /**
   * @format int32
   */
  nano?: number;
};

export type MatchAnalysisHardSoftScore = {
  constraintRef?: ConstraintRef;
  score?: HardSoftScore;
  justification?: ConstraintJustification;
};

export type Patient = {
  name?: string;
  availability?: Timeslot[];
  therapyType?: string;
  /**
   * @format int32
   */
  criticality?: number;
  location?: LatLng;
};

export type Schedule = {
  therapistList?: Therapist[];
  timeslotList?: Timeslot[];
  patientList?: Patient[];
  appointmentList?: Appointment[];
  score?: HardSoftScore;
};

export type ScoreAnalysisHardSoftScore = {
  score?: HardSoftScore;
  constraintMap?: {
    [key: string]: ConstraintAnalysisHardSoftScore;
  };
  solutionInitialized?: boolean;
};

export type SolveResponse = {
  schedule?: Schedule;
  scoreAnalysis?: ScoreAnalysisHardSoftScore;
};

export type Therapist = {
  name?: string;
  availability?: Timeslot[];
  /**
   * @format int32
   */
  maxTravelDistanceKm?: number;
  location?: LatLng;
  skills?: string[];
};

export type Timeslot = {
  /**
   * @format date
   */
  date?: string;
  startTime?: LocalTime;
  endTime?: LocalTime;
};
